version: '3.8'

services:
  web:
    build: .
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 -t 600 --keep-alive 600
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.prod