apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnky-deployment
  labels:
    app: mnky
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mnky
  template:
    metadata:
      labels:
        app: mnky
    spec:
      containers:
      - name: mnky
        image: robbycode29/api-monkeyplayin
        ports:
        - containerPort: 80
        env:
        - name: DEBUG
          value: "0"
        - name: DJANGO_ALLOWED_HOSTS
          value: "localhost 127.0.0.1"
        - name: SECRET_KEY
          value: "django-insecure-xvd1@26-(+5@1t582h4m@4h_#_5!erj22nuhsy0+tgcsec5qs3"